name: Push to main brench

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build exec
      run: |
        go build -o banai -v .
    
    - name: 'Save artifact'
      uses: actions/upload-artifact@v2
      with:
        name: banai
        path: banai
        
      
          
